### ISSUE TITLE
Problems with using LIKE expressions in a message selector

### ISSUE THREAD

**Issue by joachim-kn** [rabbitmq/rabbitmq-jms-topic-exchange#18]
We have been testing a couple of use cases with the RabbitMQ JMS client library, and found that message selectors using LIKE expressions seem not to be working as expected.

Looking into the details, we came to the conclusion that the expression that is created on the server (i.e. the rjms_erlang_selector binding argument) seems to be ok, but does not evaluate correctly.

Unfortunately my Erlang capabilities are not sufficient to provide a proper repro case here, but looking into the source code I was able to make two adjustments that fix the issue:

sjx_evaluator.erl

Instead of line 60/61:
evaluate( {'like', LHS, Patt },            Headers ) -> isLike(val_of(LHS, Headers), Patt);
evaluate( {'not_like', LHS, Patt },        Headers ) -> not3(isLike(val_of(LHS, Headers), Patt));
 
The following code has been used:
evaluate( {'like', LHS, Patt, Esc },       Headers ) -> isLike(val_of(LHS, Headers), {Patt, Esc});
evaluate( {'not_like', LHS, Patt, Esc },   Headers ) -> not3(isLike(val_of(LHS, Headers), {Patt, Esc}));

I hope this is sufficient to understand what was going wrong here?

Thanks for looking into this!

Best regards,
- Joachim

**Comment by acogoluegnes** [comment]
The fix you suggest does not break the JMS plugin test suite, nor the JMS client one, which is a good thing. You can provide an example of what was not working properly, e.g. a selector with `like` that doesn't work as expected?

**Comment by joachim-kn** [comment]
I think every LIKE (or NOT LIKE) expression should do, but to give an example:

- In Java, create a durable subscription with message selector "Country LIKE '%DE%'", then disconnect.
- This translates to a queue with the name of the durable subscription, and a binding with rjms_erlang_selector: {'like',{'ident',<<"Country">>},<<"%DE%">>,'no_escape'}.
- In the RMQ Web UI, send a message to exchange jms.durable.topic, with header Country set to "DE"

Result in the UI: "Message published, but not routed."
No message can be found in the queue created by the durable subscription.

**Comment by acogoluegnes** [comment]
Thanks, I reproduced in a test in the JMS client, it's fixed now, it should ship in 3.7.15. Thanks for the fix!

**Comment by michaelklishin** [comment]
Thank you @joachim-kn! 👏
