### ISSUE TITLE
Test flakiness

### ISSUE THREAD

**Issue by camelpunch** [rabbitmq/rabbitmq-jms-topic-exchange#8]
According to @michaelklishin, the Erlang client in tests uses basic.get instead of basic.consume. The former is timing sensitive, and could be replaced to make our builds more reliable.

Alternatively, re-tries basic.gets.

**Comment by michaelklishin** [comment]
Fixed in https://github.com/rabbitmq/rabbitmq-jms-topic-exchange/commit/e27de3b0a81c1f3db8ba0163ef87b2ffc285750f.
